name: call_link
description: "WebRTC Video Call App with Firebase"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter_webrtc: ^1.2.0   
  cloud_firestore: ^6.0.3
  firebase_core: ^4.2.0
  get_it: ^8.2.0
  uuid: ^4.2.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true